import type { AuditRecord, DashboardSummary, DeploymentRecord, PlanRecord } from "../repos/management"

const Css = () => <style>{`*{box-sizing:border-box}body{margin:0;background:#f4f1e9;color:#172033;font:15px/1.5 Georgia,serif}.side{position:fixed;inset:0 auto 0 0;width:220px;padding:28px 20px;background:#14261f;color:#fff}.side strong{display:block;font-size:22px;margin-bottom:28px}.side a{display:block;color:#dfe9df;text-decoration:none;padding:10px 12px;border-radius:8px}.side a:hover{background:#294236}.console{margin-left:220px;padding:42px;max-width:1500px}.eyebrow{text-transform:uppercase;letter-spacing:.12em;color:#687386;font:700 12px sans-serif}.console h1{font-size:38px;margin:3px 0 28px}.panel,.metric,.deployment-card{background:#fff;border:1px solid #dce0dc;border-radius:14px;box-shadow:0 3px 12px #2030250b}.panel{padding:24px;margin:20px 0}.metric-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:14px}.metric{padding:20px}.metric span{display:block;color:#687386;font:13px sans-serif}.metric b{font-size:34px}.section-head,.button-row{display:flex;justify-content:space-between;gap:12px;align-items:center}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:13px;border-bottom:1px solid #e5e7e5}th{font:700 12px sans-serif;text-transform:uppercase;color:#687386}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(180px,1fr));gap:14px;align-items:end}.compact{grid-template-columns:repeat(4,minmax(140px,1fr))}.inline-form{display:flex;gap:8px}label{display:grid;gap:6px;font-weight:700}input,select,button,.button{font:inherit;border:1px solid #cbd3ce;border-radius:8px;padding:9px 11px;background:#fff}button,.button{cursor:pointer;background:#196b4b;color:#fff;border-color:#196b4b;text-decoration:none;font-weight:700}.secondary{background:#fff;color:#196b4b}.badge{display:inline-block;border-radius:99px;padding:4px 9px;background:#e7ece9}.badge.active{color:#075c3b;background:#dff5e9}.badge.archived{color:#77421c;background:#f8eadc}.card-list{display:grid;gap:14px}.deployment-card{padding:20px}.deployment-card h3{margin:0 0 5px}@media(max-width:900px){.side{position:static;width:auto}.side a{display:inline-block}.console{margin:0;padding:22px}.metric-grid,.form-grid,.compact{grid-template-columns:1fr 1fr}}@media(max-width:600px){.metric-grid,.form-grid,.compact{grid-template-columns:1fr}.console{padding:16px}.inline-form{display:grid}}`}</style>
const Nav = () => <nav class="side"><strong>Hyphen Control</strong><a href="/operator">Dashboard</a><a href="/operator/clients">Clients</a><a href="/operator/plans">Plans</a><a href="/operator/deployments">Deployments</a><a href="/operator/contracts">Contracts</a><a href="/operator/audit">Audit</a></nav>
const Shell = (props: { title: string; children: any }) => <html><head><meta name="viewport" content="width=device-width"/><title>{props.title} · Hyphen Control</title><Css/></head><body><Nav/><main class="console"><header><p class="eyebrow">Vendor control plane</p><h1>{props.title}</h1></header>{props.children}</main></body></html>
const Csrf = (props: { token: string }) => <input type="hidden" name="_csrf" value={props.token}/>

export function ManagementDashboard({summary}: {summary: DashboardSummary}) { const cards = [["Active clients",summary.clients],["Organisations",summary.organisations],["Live deployments",summary.deployments],["Active contracts",summary.activeContracts],["Needs attention",summary.unhealthyDeployments]]; return <Shell title="Operations overview"><section class="metric-grid">{cards.map(([l,v])=><article class="metric"><span>{l}</span><b>{v}</b></article>)}</section><section class="panel"><h2>Control customer access</h2><p>Plans define the product. Contracts set dates, seats and modules. Deployments apply that signed entitlement to each customer installation.</p><div class="button-row"><a class="button" href="/operator/clients">Manage clients</a><a class="button secondary" href="/operator/deployments">Deployment health</a></div></section></Shell> }

export function PlansPage({plans,csrfToken}: {plans: PlanRecord[];csrfToken:string}) { return <Shell title="Plans"><section class="panel"><h2>Product plans</h2><p>Core CRM is always included. Optional modules are selected per contract.</p><table><thead><tr><th>Plan</th><th>Key</th><th>Contracts</th><th>Status</th><th>Actions</th></tr></thead><tbody>{plans.map(p=><tr><td colSpan={2}><form class="inline-form" method="post" action={`/operator/plans/${p.id}`}><Csrf token={csrfToken}/><input name="displayName" value={p.displayName}/><input name="planKey" value={p.planKey}/><button>Save</button></form></td><td>{p.contractCount}</td><td><span class={`badge ${p.active?"active":"archived"}`}>{p.active?"Active":"Inactive"}</span></td><td><form method="post" action={`/operator/plans/${p.id}/status`}><Csrf token={csrfToken}/><input type="hidden" name="active" value={p.active?"false":"true"}/><button class="secondary">{p.active?"Deactivate":"Restore"}</button></form></td></tr>)}</tbody></table></section><section class="panel"><h2>Create plan</h2><form class="form-grid" method="post" action="/operator/plans"><Csrf token={csrfToken}/><label>Plan name<input required name="displayName" placeholder="Core CRM"/></label><label>Stable key<input required name="planKey" pattern="[a-z0-9-]+" placeholder="core-crm"/></label><button>Create plan</button></form></section></Shell> }

export function DeploymentsPage({deployments,csrfToken}: {deployments:DeploymentRecord[];csrfToken:string}) { return <Shell title="Deployments"><section class="panel"><h2>Customer installations</h2><p>Disable an installation to stop active entitlement renewal.</p><div class="card-list">{deployments.map(d=><article class="deployment-card"><p class="eyebrow">{d.clientName}</p><h3>{d.deploymentKey}</h3><p>{d.healthStatus??"No heartbeat"} · {d.occupiedSeats??0} occupied seats · {d.lastHeartbeat??"Never connected"}</p><form class="form-grid compact" method="post" action={`/operator/deployments/${d.id}`}><Csrf token={csrfToken}/><label>Environment<input name="environment" value={d.environment}/></label><label>Status<select name="status"><option selected={d.status==="active"} value="active">Enabled</option><option selected={d.status==="disabled"} value="disabled">Disabled</option></select></label><label>Approved image digest<input name="imageDigest" value={d.imageDigest??""} placeholder="sha256:…"/></label><label>Linked contract<input disabled value={d.contractId?`${d.contractStatus} · ${d.contractId}`:"Not assigned"}/></label><button>Save deployment</button></form></article>)}</div></section></Shell> }

export function AuditPage({records}: {records:AuditRecord[]}) { return <Shell title="Audit log"><section class="panel"><table><thead><tr><th>Time</th><th>Operator</th><th>Action</th><th>Target</th></tr></thead><tbody>{records.map(r=><tr><td>{r.createdAt}</td><td>{r.operatorEmail??"System"}</td><td>{r.action}</td><td>{r.targetType} · <code>{r.targetId}</code></td></tr>)}</tbody></table></section></Shell> }
