/**
 * Regenerates app/documentation/schema-data.ts from the LIVE database schema
 * (information_schema), so the docs' schema reference states every table and
 * every column exactly as deployed. Run after any migration:
 *
 *   npm run docs:schema
 */
import { writeFileSync } from "node:fs"
import postgres from "postgres"
import "dotenv/config"

const MODULE_OF: [RegExp, string][] = [
  [/^(leads|accounts|persons)$/, "CRM"],
  [
    /^(funnels|pipelines|pipeline_stages|stage_approval_requests|funnel_stage_history|quotations|quotation_line_items|products|tax_settings|projects|payment_milestones|sales_orders|deal_costs|contract_years)$/,
    "Sales",
  ],
  [/^finance_docs$/, "Finance add-on"],
  [/^intercompany_/, "Intercompany"],
  [
    /^(tenant_settings|roles|permissions|role_permissions|membership_profiles|pending_invites|activities|attachments|audit_log|custom_field|project_counters)/,
    "Platform",
  ],
  [
    /^(user|session|account|verification|organization|member|invitation)$/,
    "Auth (Better Auth)",
  ],
]

function moduleOf(table: string): string {
  for (const [re, m] of MODULE_OF) if (re.test(table)) return m
  return "Other"
}

async function main() {
  const sql = postgres(process.env.DATABASE_URL!, { max: 1 })
  const cols = await sql<
    {
      table_name: string
      column_name: string
      data_type: string
      udt_name: string
      is_nullable: string
      column_default: string | null
    }[]
  >`
    SELECT c.table_name, c.column_name, c.data_type, c.udt_name,
           c.is_nullable, c.column_default
    FROM information_schema.columns c
    JOIN information_schema.tables t
      ON t.table_name = c.table_name AND t.table_schema = 'public'
    WHERE c.table_schema = 'public' AND t.table_type = 'BASE TABLE'
      AND c.table_name NOT LIKE 'drizzle%'
    ORDER BY c.table_name, c.ordinal_position
  `
  const enums = await sql<{ enum_name: string; labels: string[] }[]>`
    SELECT t.typname AS enum_name,
           array_agg(e.enumlabel ORDER BY e.enumsortorder) AS labels
    FROM pg_type t JOIN pg_enum e ON e.enumtypid = t.oid
    GROUP BY t.typname ORDER BY t.typname
  `
  await sql.end()

  const enumMap = Object.fromEntries(enums.map((e) => [e.enum_name, e.labels]))

  type Col = { name: string; type: string; nullable: boolean; def: string | null }
  const tables = new Map<string, Col[]>()
  for (const c of cols) {
    const list = tables.get(c.table_name) ?? []
    const type =
      c.data_type === "USER-DEFINED"
        ? `${c.udt_name} (${(enumMap[c.udt_name] ?? []).join(" | ")})`
        : c.data_type === "ARRAY"
          ? `${c.udt_name.replace(/^_/, "")}[]`
          : c.data_type
    // Trim noisy defaults ("'draft'::finance_doc_status" → "'draft'").
    const def = c.column_default
      ? c.column_default.replace(/::[a-z_ "]+(\[\])?$/i, "")
      : null
    list.push({
      name: c.column_name,
      type,
      nullable: c.is_nullable === "YES",
      def,
    })
    tables.set(c.table_name, list)
  }

  const data = [...tables.entries()]
    .map(([name, columns]) => ({ name, module: moduleOf(name), columns }))
    .sort(
      (a, b) => a.module.localeCompare(b.module) || a.name.localeCompare(b.name)
    )

  const out = `/**
 * AUTO-GENERATED by db/generate-schema-docs.ts — do not edit by hand.
 * Regenerate after any migration:  npm run docs:schema
 */
export type SchemaColumn = {
  name: string
  type: string
  nullable: boolean
  def: string | null
}
export type SchemaTable = {
  name: string
  module: string
  columns: SchemaColumn[]
}

export const SCHEMA_TABLES: SchemaTable[] = ${JSON.stringify(data, null, 2)}
`
  writeFileSync("app/documentation/schema-data.ts", out)
  console.log(
    `✓ wrote app/documentation/schema-data.ts — ${data.length} tables, ${cols.length} columns`
  )
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
